export const Paths = {
    home: '/home',
    casino: '/casino/slots',
    casinoTournaments: '/casino/tournaments',
    live: '/live_events',
    eventView: '/live_events/event-view',
    liveCalendar: '/live_events/live-calendar',
    results: '/live_events/results',
    statistics: '/live_events/statistics',
    verifyEmail: '/verify-email',
    resetPassword: '/reset-password',
    games: '/games',
    esports: '/esports',
    esportsEventView: '/esports/event-view',
    esportsLiveCalendar: '/esports/live-calendar',
    esportsResults: '/esports/results',
    esportsStatistics: '/esports/statistics',
}