//  Auth - Signup
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//  Auth - Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Auth - Logout
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// Auth - Verify Email
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";

// Auth - Get User Data
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

// Auth - Update User Balance and Exposure
export const UPDATE_USER_BALANCE_EXPOSURE = "UPDATE_USER_BALANCE_EXPOSURE";
export const UPDATE_USER_BALANCE_EXPOSURE_SUCCESS = "UPDATE_USER_BALANCE_EXPOSURE_SUCCESS";
export const UPDATE_USER_BALANCE_EXPOSURE_FAILURE = "UPDATE_USER_BALANCE_EXPOSURE_FAILURE";
