//  Auth - Signup
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//  Auth - Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Auth - Logout
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// Auth - Verify Email
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";

// Auth - Get User Data
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

// Auth - Update User Balance and Exposure
export const UPDATE_USER_BALANCE_EXPOSURE = "UPDATE_USER_BALANCE_EXPOSURE";
export const UPDATE_USER_BALANCE_EXPOSURE_SUCCESS = "UPDATE_USER_BALANCE_EXPOSURE_SUCCESS";
export const UPDATE_USER_BALANCE_EXPOSURE_FAILURE = "UPDATE_USER_BALANCE_EXPOSURE_FAILURE";

// User Bets
export const FETCH_USER_BETS = "FETCH_USER_BETS";
export const FETCH_USER_BETS_SUCCESS = "FETCH_USER_BETS_SUCCESS";
export const FETCH_USER_BETS_FAILURE = "FETCH_USER_BETS_FAILURE";
export const SKIP_NEXT_USER_BETS_FETCH = "SKIP_NEXT_USER_BETS_FETCH";

// Casino Games
export const FETCH_CASINO_GAMES = "FETCH_CASINO_GAMES";
export const FETCH_CASINO_GAMES_SUCCESS = "FETCH_CASINO_GAMES_SUCCESS";
export const FETCH_CASINO_GAMES_FAILURE = "FETCH_CASINO_GAMES_FAILURE";
export const FETCH_MORE_CASINO_GAMES = "FETCH_MORE_CASINO_GAMES";
export const FETCH_MORE_CASINO_GAMES_SUCCESS = "FETCH_MORE_CASINO_GAMES_SUCCESS";
export const FETCH_MORE_CASINO_GAMES_FAILURE = "FETCH_MORE_CASINO_GAMES_FAILURE";
export const RESET_CASINO_GAMES = "RESET_CASINO_GAMES";

// Homepage Casino Games (SUNO provider)
export const FETCH_HOMEPAGE_CASINO_GAMES = "FETCH_HOMEPAGE_CASINO_GAMES";
export const FETCH_HOMEPAGE_CASINO_GAMES_SUCCESS = "FETCH_HOMEPAGE_CASINO_GAMES_SUCCESS";
export const FETCH_HOMEPAGE_CASINO_GAMES_FAILURE = "FETCH_HOMEPAGE_CASINO_GAMES_FAILURE";

// Homepage Live Games (SPRIBE provider)
export const FETCH_HOMEPAGE_LIVE_GAMES = "FETCH_HOMEPAGE_LIVE_GAMES";
export const FETCH_HOMEPAGE_LIVE_GAMES_SUCCESS = "FETCH_HOMEPAGE_LIVE_GAMES_SUCCESS";
export const FETCH_HOMEPAGE_LIVE_GAMES_FAILURE = "FETCH_HOMEPAGE_LIVE_GAMES_FAILURE";

// Casino Providers
export const FETCH_CASINO_PROVIDERS = "FETCH_CASINO_PROVIDERS";
export const FETCH_CASINO_PROVIDERS_SUCCESS = "FETCH_CASINO_PROVIDERS_SUCCESS";
export const FETCH_CASINO_PROVIDERS_FAILURE = "FETCH_CASINO_PROVIDERS_FAILURE";
export const FETCH_MORE_CASINO_PROVIDERS = "FETCH_MORE_CASINO_PROVIDERS";
export const FETCH_MORE_CASINO_PROVIDERS_SUCCESS = "FETCH_MORE_CASINO_PROVIDERS_SUCCESS";
export const FETCH_MORE_CASINO_PROVIDERS_FAILURE = "FETCH_MORE_CASINO_PROVIDERS_FAILURE";