// User-related action types
export const ADD_USER_BALANCE_REQUEST = 'ADD_USER_BALANCE_REQUEST';
export const ADD_USER_BALANCE_SUCCESS = 'ADD_USER_BALANCE_SUCCESS';
export const ADD_USER_BALANCE_FAILURE = 'ADD_USER_BALANCE_FAILURE';

export const WITHDRAW_USER_BALANCE_REQUEST = 'WITHDRAW_USER_BALANCE_REQUEST';
export const WITHDRAW_USER_BALANCE_SUCCESS = 'WITHDRAW_USER_BALANCE_SUCCESS';
export const WITHDRAW_USER_BALANCE_FAILURE = 'WITHDRAW_USER_BALANCE_FAILURE';

export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAILURE = 'UPDATE_USER_PASSWORD_FAILURE';

export const FETCH_USER_MARKET_REPORTS_REQUEST = 'FETCH_USER_MARKET_REPORTS_REQUEST';
export const FETCH_USER_MARKET_REPORTS_SUCCESS = 'FETCH_USER_MARKET_REPORTS_SUCCESS';
export const FETCH_USER_MARKET_REPORTS_FAILURE = 'FETCH_USER_MARKET_REPORTS_FAILURE';

export const FETCH_ADMIN_USERS_REQUEST = 'FETCH_ADMIN_USERS_REQUEST';
export const FETCH_ADMIN_USERS_SUCCESS = 'FETCH_ADMIN_USERS_SUCCESS';
export const FETCH_ADMIN_USERS_FAILURE = 'FETCH_ADMIN_USERS_FAILURE';